main: main.cpp matrixHelper.cpp Model.cpp Camera.cpp common/GLShader.cpp
	g++ -o main main.cpp matrixHelper.cpp Model.cpp Camera.cpp common/GLShader.cpp \
	-lGL -lglut -lGLEW -lGLU -lglfw

clean:
	rm -f main